name: test_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2   # <-- إضافة الحزمة هنا

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assests/images/LibyaMap.png

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assests/fonts/ElMessiri-Regular.ttf
        - asset: assests/fonts/ElMessiri-semiBold.ttf
          weight: 600
        - asset: assests/fonts/ElMessiri-Bold.ttf
          weight: 700

    - family: Amiri
      fonts:
        - asset: assests/fonts/Amiri-Regular.ttf
        - asset: assests/fonts/Amiri-Bold.ttf
          weight: 700
